version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: laravel-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
